"""Lansenger SDK — framework-independent Python SDK for Lansenger Smart Bot API.

Provides async (LansengerClient) and sync (LansengerSyncClient) clients
for sending messages, files, images, cards, and managing messages via
the Lansenger (蓝信) enterprise messaging platform.

Also provides OAuth2 helpers for user identity verification in org bot apps.

Quick start:
    # Async
    from lansenger_sdk import LansengerClient
    client = LansengerClient.from_env()
    result = await client.send_text(chat_id="user123", content="Hello")

    # Sync
    from lansenger_sdk import LansengerSyncClient
    client = LansengerSyncClient.from_env()
    result = client.send_text(chat_id="user123", content="Hello")

    # OAuth2 user auth
    client = LansengerClient(app_id="...", app_secret="...", passport_url="https://passport-xxx.domain")
    auth_url = client.build_authorize_url(redirect_uri="https://myapp.com/callback")
"""

from .account_messages import (
    send_account_message,
)
from .auth import TokenManager, UserTokenManager
from .calendars import (
    add_schedule_attendees,
    create_schedule,
    delete_schedule,
    delete_schedule_attendees,
    fetch_primary_calendar,
    fetch_schedule,
    fetch_schedule_attendees,
    fetch_schedule_list,
    update_schedule,
    update_schedule_attendee_meta,
    update_schedule_attendees,
)
from .callbacks import (
    CALLBACK_EVENT_TYPES,
    AccountSubscribeData,
    AccountUnsubscribeData,
    AppInstallData,
    AppUninstallData,
    BotGroupMessageData,
    BotPrivateMessageData,
    CallbackEvent,
    CallbackEventData,
    DataScopeData,
    DeptCreateData,
    DeptDeleteData,
    DeptModifyData,
    GroupCreateApproveData,
    ReportLocationData,
    ScheduleDeleteData,
    ScheduleModifyData,
    StaffCreateData,
    StaffDeleteData,
    StaffInfoData,
    StaffModifyData,
    TagMemberData,
    TelephoneTrackCallerData,
    TelephoneTrackData,
    UaCertCreateData,
    UaCertDeleteData,
    UserLogoutData,
    WbVisibleConfigData,
    decrypt_callback_payload,
    get_callback_event_types,
    parse_callback_payload,
    verify_callback_signature,
)
from .chats import (
    fetch_chat_list,
    fetch_chat_messages,
)
from .client import LansengerClient
from .config import LansengerConfig
from .constants import (
    API_ENDPOINTS,
    APP_MEDIA_TYPE_AUDIO,
    APP_MEDIA_TYPE_FILE,
    APP_MEDIA_TYPE_IMAGE,
    APP_MEDIA_TYPE_VIDEO,
    MEDIA_TYPE_AUDIO,
    MEDIA_TYPE_IMAGE,
    MEDIA_TYPE_VIDEO,
    OAUTH2_SCOPE_BASIC_USER_INFO,
    OAUTH2_SCOPES,
    guess_app_media_type,
    guess_media_type,
)
from .contacts import (
    fetch_department_ancestors,
    fetch_org_extra_field_ids,
    fetch_org_info,
    fetch_staff_basic_info,
    fetch_staff_detail,
    fetch_staff_id_mapping,
    search_staff,
)
from .departments import (
    fetch_department_children,
    fetch_department_detail,
    fetch_department_staffs,
)
from .exceptions import (
    LansengerAPIError,
    LansengerAuthError,
    LansengerConfigError,
    LansengerError,
    LansengerFileError,
    LansengerNetworkError,
)
from .group_messages import (
    send_group_message,
)
from .groups import (
    check_is_in_group,
    create_group,
    dismiss_group,
    fetch_group_info,
    fetch_group_list,
    fetch_group_members,
    update_group_info,
    update_group_members,
)
from .media import (
    fetch_media_path,
    upload_app_media,
)
from .models import (
    AccountMessageResult,
    AppCardParams,
    BotMessageResult,
    CalendarPrimaryResult,
    ChatGroupInfo,
    ChatListResult,
    ChatMessageInfo,
    ChatMessagesResult,
    ChatStaffInfo,
    CreateGroupResult,
    DepartmentAncestorsResult,
    DepartmentChildrenResult,
    DepartmentDetailResult,
    DepartmentStaffsResult,
    DownloadMediaResult,
    DynamicCardUpdateParams,
    ExtraFieldIdsResult,
    GroupCreateInfo,
    GroupInfoResult,
    GroupListResult,
    GroupMemberResult,
    IsInGroupResult,
    LinkCardParams,
    MediaPathResult,
    OaCardParams,
    OrgInfoResult,
    QueryGroupsResult,
    VideoconferenceConfResult,
    VideoconferenceDetailResult,
    VideoconferenceListResult,
    VideoconferenceOpResult,
    VideoconferenceParamResult,
    VideoconferenceStatusListResult,
    VideoconferenceVodListResult,
    VideoconferenceVodUrlResult,
    ScheduleAttendeeMetaResult,
    ScheduleAttendeesResult,
    ScheduleAttendeesUpdateResult,
    ScheduleCreateResult,
    ScheduleInfoResult,
    ScheduleListResult,
    ScheduleUpdateResult,
    SendMessageResult,
    StaffBasicInfoResult,
    StaffDetailResult,
    StaffIdMappingResult,
    StaffSearchResult,
    StreamMessageResult,
    UpdateGroupMembersResult,
    UpdateGroupResult,
    UploadMediaResult,
    UserInfoResult,
    UserMessageResult,
    UserTokenResult,
)
from .videoconferences import (
    VC_CREATE_SOURCE_CLIENT,
    VC_CREATE_SOURCE_THIRD_PARTY,
    VC_FETCH_RANGE_ALL,
    VC_FETCH_RANGE_MY,
    VC_FETCH_RANGE_PERSON,
    VC_MEMBER_ROLE_HOST,
    VC_MEMBER_ROLE_MEMBER,
    VC_OPS,
    cancel_meeting,
    control_member,
    create_meeting,
    fetch_active_meetings,
    fetch_history_meetings,
    fetch_meeting_detail,
    fetch_meeting_list,
    fetch_meeting_params,
    fetch_meeting_record_list,
    fetch_meeting_status,
    fetch_member_list,
    fetch_member_simplerecord,
    fetch_org_conf,
    fetch_vod_download_urls,
    fetch_vod_list,
    invite_members,
    modify_meeting,
    stop_meeting,
    subscribe_meeting_events,
)
from .oauth import (
    build_authorize_url,
    exchange_code_for_user_token,
    parse_authorize_callback,
    refresh_user_token,
    validate_callback_state,
)
from .persistence import CredentialStore, VALID_IDENTITY_TYPES
from .reminders import (
    REMINDER_TYPE_NONE,
    REMINDER_TYPE_PHONE,
    REMINDER_TYPE_POPUP,
    REMINDER_TYPE_SMS,
    send_reminder,
)
from .streaming import (
    create_stream_message,
    fetch_stream_message,
)
from .sync_client import LansengerSyncClient
from .user_messages import (
    send_user_message,
)
from .users import fetch_user_info

__all__ = [
    "LansengerClient",
    "LansengerSyncClient",
    "LansengerConfig",
    "SendMessageResult",
    "QueryGroupsResult",
    "UploadMediaResult",
    "DownloadMediaResult",
    "AppCardParams",
    "LinkCardParams",
    "MediaPathResult",
    "VideoconferenceConfResult",
    "VideoconferenceDetailResult",
    "VideoconferenceListResult",
    "VideoconferenceOpResult",
    "VideoconferenceParamResult",
    "VideoconferenceStatusListResult",
    "VideoconferenceVodListResult",
    "VideoconferenceVodUrlResult",
    "OaCardParams",
    "DynamicCardUpdateParams",
    "UserTokenResult",
    "UserInfoResult",
    "StaffBasicInfoResult",
    "StaffDetailResult",
    "DepartmentAncestorsResult",
    "StaffIdMappingResult",
    "OrgInfoResult",
    "CalendarPrimaryResult",
    "ScheduleCreateResult",
    "ScheduleInfoResult",
    "ScheduleListResult",
    "ScheduleAttendeesResult",
    "ScheduleAttendeesUpdateResult",
    "ScheduleAttendeeMetaResult",
    "ScheduleUpdateResult",
    "ExtraFieldIdsResult",
    "StaffSearchResult",
    "AccountMessageResult",
    "BotMessageResult",
    "UserMessageResult",
    "StreamMessageResult",
    "GroupCreateInfo",
    "CreateGroupResult",
    "GroupInfoResult",
    "GroupMemberResult",
    "GroupListResult",
    "IsInGroupResult",
    "UpdateGroupResult",
    "UpdateGroupMembersResult",
    "DepartmentDetailResult",
    "DepartmentChildrenResult",
    "DepartmentStaffsResult",
    "ChatStaffInfo",
    "ChatGroupInfo",
    "ChatListResult",
    "ChatMessageInfo",
    "ChatMessagesResult",
    "LansengerError",
    "LansengerConfigError",
    "LansengerAuthError",
    "LansengerAPIError",
    "LansengerNetworkError",
    "LansengerFileError",
    "API_ENDPOINTS",
    "OAUTH2_SCOPE_BASIC_USER_INFO",
    "OAUTH2_SCOPES",
    "MEDIA_TYPE_VIDEO",
    "MEDIA_TYPE_IMAGE",
    "MEDIA_TYPE_AUDIO",
    "APP_MEDIA_TYPE_VIDEO",
    "APP_MEDIA_TYPE_IMAGE",
    "APP_MEDIA_TYPE_FILE",
    "APP_MEDIA_TYPE_AUDIO",
    "guess_media_type",
    "guess_app_media_type",
    "build_authorize_url",
    "exchange_code_for_user_token",
    "refresh_user_token",
    "parse_authorize_callback",
    "validate_callback_state",
    "fetch_user_info",
    "fetch_staff_basic_info",
    "fetch_staff_detail",
    "fetch_department_ancestors",
    "fetch_staff_id_mapping",
    "fetch_org_extra_field_ids",
    "search_staff",
    "fetch_org_info",
    "fetch_primary_calendar",
    "create_schedule",
    "fetch_schedule",
    "update_schedule",
    "delete_schedule",
    "fetch_schedule_list",
    "fetch_schedule_attendees",
    "add_schedule_attendees",
    "delete_schedule_attendees",
    "update_schedule_attendee_meta",
    "update_schedule_attendees",
    "create_group",
    "fetch_group_info",
    "fetch_group_members",
    "fetch_group_list",
    "check_is_in_group",
    "update_group_info",
    "update_group_members",
    "dismiss_group",
    "fetch_department_detail",
    "fetch_department_children",
    "fetch_department_staffs",
    "create_stream_message",
    "fetch_stream_message",
    "send_account_message",
    "send_user_message",
    "fetch_media_path",
    "upload_app_media",
    "VC_CREATE_SOURCE_CLIENT",
    "VC_CREATE_SOURCE_THIRD_PARTY",
    "VC_FETCH_RANGE_ALL",
    "VC_FETCH_RANGE_MY",
    "VC_FETCH_RANGE_PERSON",
    "VC_MEMBER_ROLE_HOST",
    "VC_MEMBER_ROLE_MEMBER",
    "VC_OPS",
    "cancel_meeting",
    "control_member",
    "create_meeting",
    "fetch_active_meetings",
    "fetch_history_meetings",
    "fetch_meeting_detail",
    "fetch_meeting_list",
    "fetch_meeting_params",
    "fetch_meeting_record_list",
    "fetch_meeting_status",
    "fetch_member_list",
    "fetch_member_simplerecord",
    "fetch_org_conf",
    "fetch_vod_download_urls",
    "fetch_vod_list",
    "invite_members",
    "modify_meeting",
    "stop_meeting",
    "subscribe_meeting_events",
    "send_reminder",
    "REMINDER_TYPE_NONE",
    "REMINDER_TYPE_POPUP",
    "REMINDER_TYPE_SMS",
    "REMINDER_TYPE_PHONE",
    "parse_callback_payload",
    "verify_callback_signature",
    "decrypt_callback_payload",
    "get_callback_event_types",
    "CallbackEvent",
    "CallbackEventData",
    "CALLBACK_EVENT_TYPES",
    "AccountSubscribeData",
    "AccountUnsubscribeData",
    "StaffInfoData",
    "StaffModifyData",
    "StaffCreateData",
    "StaffDeleteData",
    "TelephoneTrackData",
    "TelephoneTrackCallerData",
    "DeptCreateData",
    "DeptModifyData",
    "DeptDeleteData",
    "AppInstallData",
    "AppUninstallData",
    "UaCertCreateData",
    "UaCertDeleteData",
    "ReportLocationData",
    "UserLogoutData",
    "DataScopeData",
    "BotPrivateMessageData",
    "BotGroupMessageData",
    "WbVisibleConfigData",
    "GroupCreateApproveData",
    "ScheduleModifyData",
    "ScheduleDeleteData",
    "TagMemberData",
    "CredentialStore",
    "VALID_IDENTITY_TYPES",
    "TokenManager",
    "UserTokenManager",
    "fetch_chat_list",
    "fetch_chat_messages",
]

__version__ = "1.10.2"
